[2024-07-17T09:03:51.585+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-17T09:03:51.647+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: computer_data.insert_memory_data_task scheduled__2024-07-17T09:00:00+00:00 [queued]>
[2024-07-17T09:03:51.664+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: computer_data.insert_memory_data_task scheduled__2024-07-17T09:00:00+00:00 [queued]>
[2024-07-17T09:03:51.667+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-17T09:03:51.693+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_memory_data_task> on 2024-07-17 09:00:00+00:00
[2024-07-17T09:03:51.717+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=48) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-17T09:03:51.722+0000] {standard_task_runner.py:63} INFO - Started process 50 to run task
[2024-07-17T09:03:51.723+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'computer_data', 'insert_memory_data_task', 'scheduled__2024-07-17T09:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/collect_to_postgre_dag.py', '--cfg-path', '/tmp/tmp2jrz19ep']
[2024-07-17T09:03:51.727+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask insert_memory_data_task
[2024-07-17T09:03:51.842+0000] {task_command.py:426} INFO - Running <TaskInstance: computer_data.insert_memory_data_task scheduled__2024-07-17T09:00:00+00:00 [running]> on host a1dc1d780113
[2024-07-17T09:03:52.013+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='computer_data' AIRFLOW_CTX_TASK_ID='insert_memory_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-17T09:00:00+00:00'
[2024-07-17T09:03:52.021+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-17T09:03:52.044+0000] {logging_mixin.py:188} INFO - Error: relation "memory" does not exist
LINE 2:                INSERT INTO memory (date,Hour,minute,availabl...
                                   ^
[2024-07-17T09:03:52.048+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-17T09:03:52.050+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-17T09:03:52.062+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=computer_data, task_id=insert_memory_data_task, run_id=scheduled__2024-07-17T09:00:00+00:00, execution_date=20240717T090000, start_date=20240717T090351, end_date=20240717T090352
[2024-07-17T09:03:52.146+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-17T09:03:52.493+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-17T09:03:52.551+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
