[2024-07-17T08:48:25.996+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-17T08:48:26.143+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: computer_data.insert_memory_data_task scheduled__2024-07-17T08:45:00+00:00 [queued]>
[2024-07-17T08:48:26.155+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: computer_data.insert_memory_data_task scheduled__2024-07-17T08:45:00+00:00 [queued]>
[2024-07-17T08:48:26.157+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-17T08:48:26.194+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_memory_data_task> on 2024-07-17 08:45:00+00:00
[2024-07-17T08:48:26.266+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=77) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-17T08:48:26.274+0000] {standard_task_runner.py:63} INFO - Started process 86 to run task
[2024-07-17T08:48:26.285+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'computer_data', 'insert_memory_data_task', 'scheduled__2024-07-17T08:45:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/collect_to_postgre_dag.py', '--cfg-path', '/tmp/tmpwe6xzv93']
[2024-07-17T08:48:26.294+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask insert_memory_data_task
[2024-07-17T08:48:26.596+0000] {task_command.py:426} INFO - Running <TaskInstance: computer_data.insert_memory_data_task scheduled__2024-07-17T08:45:00+00:00 [running]> on host 89d76cef5c61
[2024-07-17T08:48:27.024+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='computer_data' AIRFLOW_CTX_TASK_ID='insert_memory_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T08:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-17T08:45:00+00:00'
[2024-07-17T08:48:27.046+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-17T08:48:27.064+0000] {logging_mixin.py:188} INFO - Error: relation "memory" does not exist
LINE 2:                INSERT INTO memory (date,Hour,minute,availabl...
                                   ^
[2024-07-17T08:48:27.065+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-17T08:48:27.067+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-17T08:48:27.130+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=computer_data, task_id=insert_memory_data_task, run_id=scheduled__2024-07-17T08:45:00+00:00, execution_date=20240717T084500, start_date=20240717T084826, end_date=20240717T084827
[2024-07-17T08:48:27.229+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-17T08:48:27.297+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-17T08:48:27.299+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
