[2024-07-16T15:54:41.679+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-16T15:54:41.717+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: computer_data.insert_battery_data_task scheduled__2024-07-16T15:30:00+00:00 [queued]>
[2024-07-16T15:54:41.730+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: computer_data.insert_battery_data_task scheduled__2024-07-16T15:30:00+00:00 [queued]>
[2024-07-16T15:54:41.730+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-16T15:54:41.753+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_battery_data_task> on 2024-07-16 15:30:00+00:00
[2024-07-16T15:54:41.820+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=106) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-16T15:54:41.822+0000] {standard_task_runner.py:63} INFO - Started process 116 to run task
[2024-07-16T15:54:41.839+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'computer_data', 'insert_battery_data_task', 'scheduled__2024-07-16T15:30:00+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/collect_to_postgre_dag.py', '--cfg-path', '/tmp/tmpy045rl5p']
[2024-07-16T15:54:41.850+0000] {standard_task_runner.py:91} INFO - Job 103: Subtask insert_battery_data_task
[2024-07-16T15:54:41.930+0000] {task_command.py:426} INFO - Running <TaskInstance: computer_data.insert_battery_data_task scheduled__2024-07-16T15:30:00+00:00 [running]> on host 6be7bf2666ab
[2024-07-16T15:54:42.035+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='computer_data' AIRFLOW_CTX_TASK_ID='insert_battery_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-16T15:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-16T15:30:00+00:00'
[2024-07-16T15:54:42.063+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-16T15:54:42.070+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-16T15:54:42.071+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/battery.py", line 20, in insert_battery_data
    data_to_insert = transform_battery(collect_data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/battery.py", line 14, in transform_battery
    lst.append(battery_list[2])
               ~~~~~~~~~~~~^^^
IndexError: list index out of range
[2024-07-16T15:54:42.093+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=computer_data, task_id=insert_battery_data_task, run_id=scheduled__2024-07-16T15:30:00+00:00, execution_date=20240716T153000, start_date=20240716T155441, end_date=20240716T155442
[2024-07-16T15:54:42.114+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 103 for task insert_battery_data_task (list index out of range; 116)
[2024-07-16T15:54:42.161+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-16T15:54:42.198+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-16T15:54:42.199+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
